FROM node:22-alpine AS deps

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run check

RUN npm run build

FROM node:22-alpine

WORKDIR /app

COPY --from=deps /app ./

EXPOSE 3000

CMD ["npm", "start"]